apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /sandbox/platform-engineering/grafana-admin-password
        property: password
    - secretKey: username
      remoteRef:
        key: /sandbox/platform-engineering/grafana-admin-password
        property: username
